### ISSUE TITLE
Consider compatibility with older versions of PHP

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-php#13]
- PHP 5.6?

Input needed. Please leave a comment.

**Comment by Mosnar** [comment]
I would strongly suggest PHP 7 compatibility at least. As it is, UrlBuilder.php is using `public const` which is a PHP 7.1 feature.

**Comment by dusekdan** [comment]
As is mentioned in #60, there is one, PHP version specific problem in one of our dependencies (sunra/php-simple-html-dom-parser). When using PHP v7.1.13, library gets stuck in an endless loop calling its __destruct function all the time. See linked issue for details.

I also vote for considering support of PHPv7.

**Comment by petrsvihlik** [comment]
Based on [PHP usage stats per version](https://seld.be/notes/php-versions-stats-2018-1-edition) and [PHP support cycle](http://php.net/supported-versions.php) we decided that supporting PHP 7 and onward should be fine. We won't be making the SDK compatible with PHP 5.x.
