### ISSUE TITLE
2nd review

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-php#39]
- do a thorough review of the PHP SDK (especially of the content item retrieval/binding part)

**Comment by dusekdan** [comment]
I started reviewing the code, here is what I have to discuss so far:
* We currently have `ValueConverterInterface`, `TypeMapperInterface` and `PropertyMapperInterface`, but I don't see any way to pass my own ValueConverter/TypeMapper/PropertyMapper implementation to DeliveryClient. Is this what #42 is about?

**Comment by petrsvihlik** [comment]
- you can pass the implementation to public properties of the `DeliveryClient`  right after you construct it... shall we add it to the constructor? or what do you propose?

**Comment by Simply007** [comment]
@dusekdan closed issue on the board - closing this one.
