### ISSUE TITLE
Get by type then filter by element 

### ISSUE THREAD

**Issue by MiraiTunga** [Kentico/delivery-sdk-php#59]
How do we get items by type then filter e.g

```
  getItems((new QueryParams())->type('A') ->equals('name', 'bob'));
```
Are they any examples ? 

Thanks

**Comment by petrsvihlik** [comment]
Hi @MiraiTunga 
you can do it like this:

```
$response = $client->getItems((new QueryParams())
  ->equals('system.type', 'A')
  ->equals('name', 'bob');
```

or

```
$response = $client->getItems((new QueryParams())
  ->type('A, B, C')
  ->equals('name', 'bob');
```
for more types.

You can find more examples in the documentation: https://developer.kenticocloud.com/v1/reference#list-content-items
