### ISSUE TITLE
Mistake in README

### ISSUE THREAD

**Issue by MartinaFarkasova** [Kentico/delivery-sdk-php#76]
### Brief bug description

Customer reported an issue in the Readme file saying:

> The "The language selection is just a matter of specifying one additional filtering parameter to the query." was directly copied and pasted into the taxonomy section without changing.

### Repro steps

1. Go to 'delivery-sdk-php/README.md'
2. Scroll down to 'Working with taxonomies'
4. The text was just copied from 'Getting localized items'.

**Comment by petrsvihlik** [comment]
done
