### ISSUE TITLE
Improve the installation guidance

### ISSUE THREAD

**Issue by HarryAdney** [Kentico/delivery-sdk-php#78]
### Motivation

It'll help people, like me, who are new to installing php on Windows.

### Proposed solution

Add the location in php.ini to add the "zend_extension = ext\php_xdebug-2.7.0-7.3-vc15-nts-x86_64.dll" line

### Additional context

(https://github.com/Kentico/delivery-sdk-php/wiki/Developing-PHP-in-Visual-Studio-Code-for-Dummies)

**Comment by ImSeaWorld** [comment]
Not to hijack, but to add to this, I had an issue with PowerShell recognizing `php` so after looking around, then finally looking on the xdebug page, they suggest using `phpinfo()` which can be done by running php.exe and typing `phpinfo();`. Little work around for those who had the same issue.

**Comment by petrsvihlik** [comment]
@HarryAdney do you mean adding the `ext\` relative path?

@ImSeaWorld what exactly is wrong with what's written [here](https://github.com/Kentico/delivery-sdk-php/wiki/Developing-PHP-in-Visual-Studio-Code-for-Dummies#install-xdebug)?  how would you adjust the steps?

**Comment by ImSeaWorld** [comment]
@petrsvihlik I would add a disclaimer to step 3. Maybe something like this.

> 3. Run `php -i` _(If you receive an error `'php' not recognized` continue to step 3.1)_
> _3.1. Open `c:\php\php.exe`_
> _3.2. Input `phpinfo();` press enter (Continue to step 4)_

**Comment by HarryAdney** [comment]
> @HarryAdney do you mean adding the `ext\` relative path?
> 
> @ImSeaWorld what exactly is wrong with what's written [here](https://github.com/Kentico/delivery-sdk-php/wiki/Developing-PHP-in-Visual-Studio-Code-for-Dummies#install-xdebug)? how would you adjust the steps?

Step 8. WHERE, exactly in php.ini to add that line. 

FYI, after following the steps, there is no [XDebug] in my php.ini

**Comment by HarryAdney** [comment]
Step 8. WHERE exactly in php.ini does the line `zend_extension = C:\php\ext\php_xdebug-2.7.0-7.3-vc15-nts-x86_64.dll` go? It isn't shown on the wizard page either, and since in bullet 5 of the INSTALL XDEBUG reads "which basically says", I think it would be useful to advise where to put the line.

FYI, I'll also contact XDebug to see if they'll add the extra advice.

**Comment by petrsvihlik** [comment]
@HarryAdney it doesn't really matter where the XDebug section is within the file. I've adjusted the description.
@ImSeaWorld thanks, adjusted

Thanks guys for your suggestions, I've incorporated both of them to the article. I also invited you to the Kentico organization, in case you want to stay up to date with our OS projects.
