### ISSUE TITLE
Implement Rich-text Modular Content Resolvers

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-php#8]
The goals is to create some kind of interface or event that a developer can hook into to resolve the inline modular content in rich-text elements.

Similarly to: 

 - .NET SDK - [code](https://github.com/Kentico/delivery-sdk-net/tree/master/KenticoCloud.Delivery/InlineContentItems) + [documentation](https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering)
 - Java SDK - [code](https://github.com/Kentico/delivery-sdk-java/search?utf8=%E2%9C%93&q=InlineContentItemsResolver&type=) 
 - TypeScript SDK [code](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/blob/2792eda7c0f5b9b7ac577500646aa99e55443e73/lib/fields/rich-text-resolver.class.ts) + [documentation](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#resolving-modular-content-in-rich-text-fields)

DoD:
- unit (and/or e2e) tests
- documentation (code examples in the readme or dedicated gh wiki page)

**Comment by Simply007** [comment]
Inline assets in rich text editor are resolved to the image tags by default, so no extension point is required for them. .net SDK does not have it neither.
