### ISSUE TITLE
Create API Documentation

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-php#9]
Use phpDocumentor

Remaining:
- [x] Add phpdoc-style comments
- [x] Generate the documentation
- [ ] Create a script and hook it to the CI (the process is described at https://github.com/Kentico/delivery-sdk-php/wiki/Generate-documentation-manually)
- [ ] Make it publicly accessible at https://github.com/Kentico/kentico.github.io/tree/master/phpsdk

Resources:
- https://www.phpdoc.org/
- https://github.com/stephenr85/KenticoCloud.Deliver.PHP/tree/master/docs

**Comment by RadoslavCap** [comment]
Pay attention to use phpDocumentator from PEAR, it's corrupted. You will get "Fatal error: Failed opening required "dompdf_config.inc.php" in Bootstrap.php on line 178" error message. There is a workaround: https://github.com/phpDocumentor/phpDocumentor2/issues/1887

**Comment by RadoslavCap** [comment]
fixes with commit dfc6b9683826f101c5ab9bb2e015856a74948346

**Comment by petrsvihlik** [comment]
Remaining:
- [ ] Hook it to the CI
- [ ] Make it publicly accessible
